source 'https://github.com/CocoaPods/Specs'

workspace 'VideoQuickStart'

abstract_target 'TwilioVideo' do
  pod 'TwilioVideo', '~> 3.0'

  target 'ReplayKitExample' do
    platform :ios, '11.0'
    project 'ReplayKitExample.xcodeproj'
  end
  
end
